"""Pipeline lookup, package export and delivery (Git handoff) configuration/plan."""
from __future__ import annotations

from typing import Any, Literal

from fastapi import HTTPException
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.orm import Session

from ..models import PipelineDefinition, PipelineVersion, Project, User
from ..pipeline_codegen import PipelineGenerationError, build_exported_package
from ..schemas import PipelinePackageDeliveryConfigSave
from .authz import require_current_project


def _get_project_pipeline_with_version(
    pipeline_id: str,
    *,
    user: User,
    db: Session,
) -> tuple[Project, PipelineDefinition, PipelineVersion]:
    project = require_current_project(db, user)
    pipeline = db.get(PipelineDefinition, pipeline_id)
    if pipeline is None or pipeline.project_id != project.id or pipeline.status == "deleted":
        raise HTTPException(status_code=404, detail="Pipeline not found")
    version = db.scalar(
        select(PipelineVersion).where(
            PipelineVersion.pipeline_id == pipeline.id,
            PipelineVersion.version == pipeline.current_version,
        )
    )
    if version is None:
        raise HTTPException(status_code=409, detail="Pipeline has no versioned definition")
    return project, pipeline, version


def _build_pipeline_package_or_404(
    pipeline: PipelineDefinition,
    version: PipelineVersion,
    package_target: Literal["postgres_view", "dbt", "dataform"],
) -> dict[str, Any]:
    definition = version.definition or {}
    target = definition.get("target", {})
    sources = definition.get("sources", [])
    artifacts = definition.get("artifacts", [])
    if not artifacts:
        raise HTTPException(status_code=404, detail="Pipeline package artifacts were not generated")
    delivery_config = _delivery_config_for_target(definition, package_target)
    try:
        package = build_exported_package(
            pipeline_name=pipeline.name,
            pipeline_version=pipeline.current_version,
            package_target=package_target,
            target_schema=str(target.get("schema", "curated")),
            target_table=str(target.get("table", "pipeline_output")),
            source_count=len(sources),
            artifacts=artifacts,
            delivery_config=delivery_config,
        )
    except PipelineGenerationError as exc:
        raise HTTPException(status_code=exc.status_code, detail=exc.detail)
    return {
        **package.as_dict(),
        "delivery_config": delivery_config,
        "delivery_plan": _build_delivery_plan(
            pipeline_name=pipeline.name,
            pipeline_version=pipeline.current_version,
            package_target=package_target,
            delivery_config=delivery_config,
        ),
    }


def _default_delivery_config(
    package_target: Literal["postgres_view", "dbt", "dataform"],
) -> dict[str, Any]:
    branch_template = (
        f"datapilot/{package_target}/{{pipeline_slug}}/v{{pipeline_version}}"
        if package_target != "postgres_view"
        else f"datapilot/sql/{{pipeline_slug}}/v{{pipeline_version}}"
    )
    pr_title = "Export {pipeline_name} ({package_target}) v{pipeline_version}"
    return {
        "delivery_mode": "download_only",
        "git_repository": None,
        "git_provider": None,
        "base_branch": "main",
        "export_subdirectory": None,
        "create_branch": False,
        "branch_strategy": "none",
        "branch_name_template": branch_template,
        "create_pr": False,
        "pr_title_template": pr_title,
        "pr_body_template": (
            "Generated by DataPilot.\n\n"
            "- Pipeline: {pipeline_name}\n"
            "- Target: {package_target}\n"
            "- Version: {pipeline_version}\n"
        ),
    }


def _normalize_delivery_config(
    package_target: Literal["postgres_view", "dbt", "dataform"],
    payload: dict[str, Any] | PipelinePackageDeliveryConfigSave | None,
) -> dict[str, Any]:
    config = _default_delivery_config(package_target)
    if payload:
        values = payload.model_dump() if isinstance(payload, BaseModel) else dict(payload)
        for key, value in values.items():
            if key in config:
                config[key] = value
    for key in ("git_repository", "export_subdirectory", "branch_name_template", "pr_title_template", "pr_body_template"):
        if isinstance(config.get(key), str):
            config[key] = config[key].strip() or None
    if config["delivery_mode"] == "download_only":
        config["create_branch"] = False
        config["create_pr"] = False
        config["branch_strategy"] = "none"
    if config["delivery_mode"] == "git_prepare":
        if not config.get("git_repository"):
            raise HTTPException(status_code=422, detail="A git_repository is required when delivery_mode is git_prepare")
        if config["create_pr"] and not config["create_branch"]:
            raise HTTPException(status_code=422, detail="create_pr requires create_branch to be enabled")
        if config["create_branch"] and config["branch_strategy"] == "none":
            config["branch_strategy"] = "timestamped"
        if config["branch_strategy"] == "custom" and not config.get("branch_name_template"):
            raise HTTPException(status_code=422, detail="branch_name_template is required when branch_strategy is custom")
    return config


def _delivery_config_for_target(
    definition: dict[str, Any],
    package_target: Literal["postgres_view", "dbt", "dataform"],
) -> dict[str, Any]:
    package_delivery = definition.get("package_delivery", {})
    stored = package_delivery.get(package_target)
    return _normalize_delivery_config(package_target, stored)


def _build_delivery_plan(
    *,
    pipeline_name: str,
    pipeline_version: int,
    package_target: Literal["postgres_view", "dbt", "dataform"],
    delivery_config: dict[str, Any],
) -> list[dict[str, str]]:
    mode = str(delivery_config.get("delivery_mode", "download_only"))
    plan = [
        {
            "step": "Export package archive",
            "status": "configured",
            "detail": f"Package target {package_target} will be exported as a downloadable bundle.",
        }
    ]
    if mode == "download_only":
        plan.append(
            {
                "step": "Manual repository handoff",
                "status": "optional",
                "detail": "No Git operations are configured; the exported bundle can be reviewed or pushed manually.",
            }
        )
        return plan
    repository = str(delivery_config.get("git_repository") or "")
    plan.append(
        {
            "step": "Prepare repository destination",
            "status": "configured",
            "detail": f"Repository metadata is stored for future export into {repository}.",
        }
    )
    if delivery_config.get("create_branch"):
        strategy = str(delivery_config.get("branch_strategy", "timestamped"))
        template = str(delivery_config.get("branch_name_template") or "")
        plan.append(
            {
                "step": "Prepare branch name",
                "status": "configured",
                "detail": f"Branch creation is enabled with {strategy} strategy using template `{template}`.",
            }
        )
    if delivery_config.get("create_pr"):
        title_template = str(delivery_config.get("pr_title_template") or "")
        plan.append(
            {
                "step": "Prepare PR metadata",
                "status": "configured",
                "detail": f"PR creation is enabled with title template `{title_template}`.",
            }
        )
    else:
        plan.append(
            {
                "step": "PR creation",
                "status": "optional",
                "detail": "PR metadata is not enabled for this package configuration.",
            }
        )
    plan.append(
        {
            "step": "External Git integration",
            "status": "not_executed",
            "detail": f"DataPilot stores this plan only; no branch or PR is created as of August 2, 2026.",
        }
    )
    return plan
